vich_uploader:
    db_driver: orm

    mappings:
       tuto_image:
           uri_prefix: /uploads/images
           upload_destination: '%kernel.project_dir%/public/images/tuto'
           delete_on_remove: true
           delete_on_update: true
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       content_image:
           uri_prefix: /uploads/images
           upload_destination: '%kernel.project_dir%/public/images/content'
           delete_on_remove: true
           delete_on_update: true
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
